/**
 * Smart Canteen System - MGM College of Engineering & Technology, Navi Mumbai
 * Menu, Combos, and Canteen Data
 */

const CANTEEN_DATA = {
    collegeInfo: {
        name: "Mahatma Gandhi Mission College of Engineering & Technology",
        shortName: "MGMCET Smart Canteen",
        campus: "Navi Mumbai, Kamothe",
        tagline: "Pursuit of Excellence • Fresh, Fast & Hygienic",
        timings: "Monday – Saturday: 7:30 AM – 6:30 PM",
        contact: "+91 22 2743 3403 | canteen@mgmmumbai.ac.in",
        location: "Ground Floor, Academic Block B, MGMCET Campus"
    },

    categories: [
        { id: "all", name: "All Items", icon: "🍽️" },
        { id: "combos", name: "Campus Combos", icon: "🔥" },
        { id: "breakfast", name: "Breakfast & Snacks", icon: "🥪" },
        { id: "south_indian", name: "South Indian", icon: "🥞" },
        { id: "meals", name: "Meals & Thali", icon: "🍛" },
        { id: "sandwiches", name: "Sandwiches & Rolls", icon: "🌯" },
        { id: "beverages", name: "Chai & Beverages", icon: "☕" },
        { id: "desserts", name: "Desserts & Coolers", icon: "🍨" }
    ],

    menuItems: [
        // Combos
        {
            id: 1,
            name: "Engineer's Fuel Combo",
            category: "combos",
            price: 49,
            originalPrice: 65,
            rating: 4.9,
            reviewsCount: 342,
            prepTime: "3-5 mins",
            calories: "380 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "2 Hot crispy Mumbai Vada Pavs + 1 Special Cutting Masala Chai. The ultimate exam day lifesaver.",
            image: "Public/images/vada_pav_combo.jpg"
        },
        {
            id: 2,
            name: "MGM Mahabhojan Special Thali",
            category: "combos",
            price: 120,
            originalPrice: 150,
            rating: 4.8,
            reviewsCount: 512,
            prepTime: "8-10 mins",
            calories: "720 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Paneer Sabji + Dal Tadka + 3 Butter Rotis + Steamed Jeera Rice + Gulab Jamun + Papad & Salad.",
            image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 3,
            name: "Exam Rush Sandwich & Cold Coffee",
            category: "combos",
            price: 89,
            originalPrice: 110,
            rating: 4.7,
            reviewsCount: 220,
            prepTime: "5-7 mins",
            calories: "450 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Jumbo Grilled Veg Cheese Sandwich with Mint Chutney served alongside thick chilled Cold Coffee.",
            image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 4,
            name: "Chinese Bhel & Mango Cooler Combo",
            category: "combos",
            price: 75,
            originalPrice: 95,
            rating: 4.6,
            reviewsCount: 168,
            prepTime: "4-6 mins",
            calories: "390 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: false,
            inStock: true,
            description: "Crispy fried noodles tossed in spicy Schezwan sauce paired with refreshing Aam Panna cooler.",
            image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
        },

        // Breakfast & Snacks
        {
            id: 5,
            name: "Mumbai Batata Vada Pav (Single)",
            category: "breakfast",
            price: 18,
            originalPrice: 20,
            rating: 4.9,
            reviewsCount: 890,
            prepTime: "2 mins",
            calories: "190 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Iconic spiced potato fritter inside fresh pav with garlic dry chutney, mint dip and fried green chili.",
            image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 6,
            name: "Kolhapuri Misal Pav with Farsan",
            category: "breakfast",
            price: 55,
            originalPrice: 65,
            rating: 4.8,
            reviewsCount: 430,
            prepTime: "5-7 mins",
            calories: "420 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Zesty sprouted moth curry topped with crunchy farsan, diced onions, fresh coriander, and 2 buttered pavs.",
            image: "Public/images/kolhapuri_misal_pav.jpg"
        },
        {
            id: 7,
            name: "Indori Kanda Poha",
            category: "breakfast",
            price: 30,
            originalPrice: 35,
            rating: 4.7,
            reviewsCount: 310,
            prepTime: "3 mins",
            calories: "220 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Flattened rice tempered with mustard seeds, curry leaves, roasted peanuts, topped with Ratlami sev and fresh lime.",
            image: "Public/images/kanda_poha.jpg"
        },
        {
            id: 8,
            name: "Punjabi Samosa Chaat",
            category: "breakfast",
            price: 45,
            originalPrice: 50,
            rating: 4.8,
            reviewsCount: 360,
            prepTime: "4-5 mins",
            calories: "340 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Crushed golden samosas layered with warm spiced chole, sweet tamarind chutney, curd, and nylon sev.",
            image: "Public/images/samosa_chaat.jpg"
        },
        {
            id: 9,
            name: "Crispy Medu Vada Sambar (2 Pcs)",
            category: "south_indian",
            price: 45,
            originalPrice: 50,
            rating: 4.7,
            reviewsCount: 290,
            prepTime: "4-6 mins",
            calories: "280 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Golden crispy lentil donuts served with steaming aromatic Madras sambar and fresh coconut chutney.",
            image: "Public/images/medu_vada_sambar.jpg"
        },
        {
            id: 10,
            name: "Butter Masala Dosa",
            category: "south_indian",
            price: 65,
            originalPrice: 75,
            rating: 4.9,
            reviewsCount: 610,
            prepTime: "6-8 mins",
            calories: "350 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Thin golden rice crepe smothered with Amul butter, filled with spiced potato masala, coconut chutney & sambar.",
            image: "Public/images/butter_masala_dosa.jpg"
        },
        {
            id: 11,
            name: "Steamed Idli Sambar (3 Pcs)",
            category: "south_indian",
            price: 40,
            originalPrice: 45,
            rating: 4.6,
            reviewsCount: 210,
            prepTime: "2-4 mins",
            calories: "180 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Pillow-soft fermented rice cakes served piping hot with vegetable sambar and freshly ground coconut chutney.",
            image: "Public/images/idli_sambar.jpg"
        },

        // Meals & Thali
        {
            id: 12,
            name: "Paneer Butter Masala with 3 Rotis",
            category: "meals",
            price: 95,
            originalPrice: 115,
            rating: 4.8,
            reviewsCount: 470,
            prepTime: "8-10 mins",
            calories: "580 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Tender cottage cheese cubes simmered in creamy makhani gravy served with soft whole-wheat rotis and salad.",
            image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 13,
            name: "Veg Schezwan Fried Rice & Manchurian",
            category: "meals",
            price: 90,
            originalPrice: 105,
            rating: 4.7,
            reviewsCount: 520,
            prepTime: "7-9 mins",
            calories: "620 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Wok-tossed spicy rice loaded with crunchy veggies served with 3 pieces of vegetable Manchurian gravy.",
            image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 14,
            name: "Moong Dal Khichdi & Desi Ghee",
            category: "meals",
            price: 70,
            originalPrice: 80,
            rating: 4.6,
            reviewsCount: 180,
            prepTime: "5-7 mins",
            calories: "380 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Wholesome, soothing comfort meal served with pure cow desi ghee, roasted papad, pickle, and curd.",
            image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 15,
            name: "Hyderabadi Veg Dum Biryani with Raita",
            category: "meals",
            price: 99,
            originalPrice: 120,
            rating: 4.9,
            reviewsCount: 650,
            prepTime: "6-8 mins",
            calories: "590 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Fragrant basmati rice slow-cooked with garden vegetables, saffron, aromatic whole spices and served with cold cucumber raita.",
            image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
        },

        // Sandwiches & Fast Food
        {
            id: 16,
            name: "Bombay Veg Cheese Grilled Sandwich",
            category: "sandwiches",
            price: 60,
            originalPrice: 70,
            rating: 4.8,
            reviewsCount: 710,
            prepTime: "5 mins",
            calories: "380 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Layered with sliced beetroot, potato, cucumber, tomato, sandwich masala, loaded mozzarella cheese and mint chutney.",
            image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 17,
            name: "Cheese Butter Maggi (Double Masala)",
            category: "sandwiches",
            price: 50,
            originalPrice: 55,
            rating: 4.9,
            reviewsCount: 840,
            prepTime: "4 mins",
            calories: "360 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Campus favourite piping-hot Maggi prepared with sautéed onions, sweet corn, extra tastemaker and shredded cheese.",
            image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 18,
            name: "Paneer Tikka Frankie Roll",
            category: "sandwiches",
            price: 70,
            originalPrice: 85,
            rating: 4.7,
            reviewsCount: 390,
            prepTime: "5-6 mins",
            calories: "410 kcal",
            isVeg: true,
            isJain: false,
            isSpicy: true,
            isPopular: true,
            inStock: true,
            description: "Char-grilled marinated paneer cubes rolled in a flaky paratha with vinegar onions, chaat masala, and spicy green chutney.",
            image: "Public/images/paneer_tikka_roll.jpg"
        },

        // Chai & Beverages
        {
            id: 19,
            name: "Special Ginger & Cardamom Cutting Chai",
            category: "beverages",
            price: 15,
            originalPrice: 15,
            rating: 4.9,
            reviewsCount: 1200,
            prepTime: "1-2 mins",
            calories: "85 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Freshly brewed full-cream milk tea boiled with crushed fresh ginger root, green cardamom, and Assam tea leaves.",
            image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 20,
            name: "Classic Thick Cold Coffee with Ice Cream",
            category: "beverages",
            price: 50,
            originalPrice: 60,
            rating: 4.8,
            reviewsCount: 680,
            prepTime: "3-4 mins",
            calories: "280 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Blended espresso coffee with chilled full cream milk, Hershey's chocolate drizzle and a scoop of vanilla ice cream.",
            image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 21,
            name: "Fresh Shikanji Mint Lemonade",
            category: "beverages",
            price: 25,
            originalPrice: 30,
            rating: 4.6,
            reviewsCount: 230,
            prepTime: "2 mins",
            calories: "90 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Freshly squeezed lemon with crushed mint leaves, black salt, cumin, and chilled sparkling soda water.",
            image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80"
        },
        {
            id: 22,
            name: "Spiced Masala Buttermilk (Chaas)",
            category: "beverages",
            price: 20,
            originalPrice: 25,
            rating: 4.7,
            reviewsCount: 310,
            prepTime: "1 min",
            calories: "65 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: false,
            inStock: true,
            description: "Cool refreshing churned curd blended with roasted cumin, green chili touch, fresh mint, and rock salt.",
            image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80"
        },

        // Desserts & Coolers
        {
            id: 23,
            name: "Hot Gulab Jamun (2 Pcs with Rabdi)",
            category: "desserts",
            price: 45,
            originalPrice: 50,
            rating: 4.8,
            reviewsCount: 260,
            prepTime: "2-3 mins",
            calories: "320 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Mouth-melting khoya dumplings soaked in saffron-rose sugar syrup topped with thick pistachio rabdi.",
            image: "Public/images/hot_gulab_jamun.jpg"
        },
        {
            id: 24,
            name: "Oreo Mudslide Thick Shake",
            category: "desserts",
            price: 65,
            originalPrice: 75,
            rating: 4.9,
            reviewsCount: 440,
            prepTime: "4 mins",
            calories: "410 kcal",
            isVeg: true,
            isJain: true,
            isSpicy: false,
            isPopular: true,
            inStock: true,
            description: "Decadent milkshake made with crushed Oreo biscuits, rich chocolate syrup, and whipped cream topping.",
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80"
        }
    ],

    crowdStatus: {
        currentLevel: "moderate", // "low", "moderate", "peak"
        levels: {
            low: {
                label: "Low Rush",
                color: "#10B981",
                badgeClass: "badge-low",
                waitTime: "5 - 8 mins",
                tablesFree: "22 / 30 tables free",
                description: "Quick pickup available! The counter is clear."
            },
            moderate: {
                label: "Moderate Rush",
                color: "#F59E0B",
                badgeClass: "badge-moderate",
                waitTime: "10 - 15 mins",
                tablesFree: "12 / 30 tables free",
                description: "Normal canteen flow. Order now to skip wait!"
            },
            peak: {
                label: "Peak Lunch Rush",
                color: "#EF4444",
                badgeClass: "badge-peak",
                waitTime: "20 - 25 mins",
                tablesFree: "4 / 30 tables free",
                description: "Heavy rush during lecture break! Digital token recommended."
            }
        }
    },

    testimonials: [
        {
            name: "Aarav Sharma",
            role: "Computer Engg, 3rd Year",
            avatar: "👨‍💻",
            comment: "The digital token system changed lunch breaks completely! I order from lab and pick it up right when it's hot and ready.",
            rating: 5
        },
        {
            name: "Prof. Sunita Deshmukh",
            role: "EXTC Faculty",
            avatar: "👩‍🏫",
            comment: "The table delivery and clean online payments are wonderful. MGM Thali and ginger cutting chai are our department daily favorites.",
            rating: 5
        },
        {
            name: "Rohan Patel",
            role: "Mechanical Engg, 2nd Year",
            avatar: "⚙️",
            comment: "Vada Pav + Cutting Chai combo for ₹49 is the best deal in Navi Mumbai. Super fast counter pickup!",
            rating: 5
        }
    ],

    coupons: {
        "MGM10": { discountPercent: 10, minOrder: 50, description: "10% Off for MGM Students & Staff" },
        "FRESHER20": { discountPercent: 20, minOrder: 100, description: "20% Off on orders above ₹100" },
        "EXAMFUEL": { discountFlat: 15, minOrder: 80, description: "Flat ₹15 Off on campus combos" }
    }
};
